server:
  port: 8083

spring:
#  sql:
#    init:
#      mode: always
#      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ORDER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: configserver:http://localhost:9296

product:
  service:
    url: http://localhost:8082/product

payment:
  service:
    url: http://localhost:8081/payment

management:
  tracing:
    sampling:
      probability: 1.0  # capture 100% of traces
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans