server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ORDER-SERVICE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: configserver:http://localhost:9296

product:
  service:
    url: http://localhost:8082/product